import { FileDown, FileSpreadsheet, Minus, Plus, Trash2, X } from 'lucide-react';
import { useSpecificationStore } from '../store/specificationStore';
import { formatMoney } from '../domain/calculations';

export function SpecificationDrawer({ onQuote }: { onQuote: () => void }) {
  const { items, isOpen, close, updateQuantity, remove } = useSpecificationStore();
  const total = items.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
  if (!isOpen) return null;
  return <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><aside className="spec-drawer" aria-label="Спецификация"><header><div><h2>Спецификация</h2><p>{items.length ? `${items.length} поз. · ${items.reduce((sum, item) => sum + item.quantity, 0)} шт.` : 'Пока пусто'}</p></div><button className="icon-button" onClick={close} aria-label="Закрыть"><X /></button></header><div className="spec-items">{items.length === 0 ? <div className="empty-state"><FileSpreadsheet size={34} /><h3>Добавьте оборудование</h3><p>Позиции и их контекст Q/H сохраняются локально в браузере.</p></div> : items.map((item) => <article className="spec-item" key={item.id}><img src={item.product.image} alt="" /><div className="spec-item__body"><h3>{item.product.name}</h3><small>{item.product.sku}</small><div className="spec-context">Q {item.context.q.toFixed(1)} м³/ч · H {item.context.h.toFixed(1)} м · DN{item.context.dn}</div>{item.comment && <p>{item.comment}</p>}<div className="quantity"><button onClick={() => updateQuantity(item.id, item.quantity - 1)}><Minus size={14} /></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)}><Plus size={14} /></button><b>{formatMoney(item.product.price * item.quantity)}</b><button className="remove" onClick={() => remove(item.id)} aria-label="Удалить"><Trash2 size={16} /></button></div></div></article>)}</div><footer><div className="spec-total"><span>Итого</span><b>{formatMoney(total)}</b></div><div className="export-actions"><button disabled={!items.length} onClick={async () => { const { exportSpecificationPdf } = await import('../services/specificationExport'); exportSpecificationPdf(items); }}><FileDown size={16} />PDF</button><button disabled={!items.length} onClick={async () => { const { exportSpecificationXlsx } = await import('../services/specificationExport'); exportSpecificationXlsx(items); }}><FileSpreadsheet size={16} />XLSX</button></div><button className="button button--dark" disabled={!items.length} onClick={onQuote}>Получить КП</button></footer></aside></div>;
}
